//
//  DetailPresenter.swift
//  prueba-coppel
//
//  Created Pedro Soriano on 28/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailPresenter: DetailPresenterProtocol {

    weak private var view: DetailViewProtocol?
    var interactor: DetailInteractorProtocol?
    private let router: DetailWireframeProtocol

    init(interface: DetailViewProtocol, interactor: DetailInteractorProtocol?, router: DetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func fetchTV(id: Int) {
        interactor?.fetchTV(id: id)
    }
    
    func responseTvDetail(data: DetailTV){
        view?.responseTvDetail(data: data)
    }
    
    func fetchMovie(id: Int){
        interactor?.fetchMovie(id: id)
    }
    
    func responseMovieDetail(data: DetailMovie){
        view?.responseMovieDetail(data: data)
    }
    
    func showError(title: String){
        view?.showError(title: title)
    }

}
