//
//  DetailProtocols.swift
//  prueba-coppel
//
//  Created Pedro Soriano on 28/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailWireframeProtocol: AnyObject {
    
}
//MARK: Presenter -
protocol DetailPresenterProtocol: AnyObject {
    func fetchTV(id: Int)
    func responseTvDetail(data: DetailTV)
    func fetchMovie(id: Int)
    func responseMovieDetail(data: DetailMovie)
    func showError(title: String)
}

//MARK: Interactor -
protocol DetailInteractorProtocol: AnyObject {
    var presenter: DetailPresenterProtocol?  { get set }
    func fetchTV(id: Int)
    func fetchMovie(id: Int)
}

//MARK: View -
protocol DetailViewProtocol: AnyObject {
    var presenter: DetailPresenterProtocol?  { get set }
    func responseTvDetail(data: DetailTV)
    func responseMovieDetail(data: DetailMovie)
    func showError(title: String)
}
