//
//  ProfileProtocols.swift
//  prueba-coppel
//
//  Created Pedro Soriano on 28/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ProfileWireframeProtocol: AnyObject {
    func goToDetail(id: Int?, movie: Bool)
}
//MARK: Presenter -
protocol ProfilePresenterProtocol: AnyObject {
    func goToDetail(id: Int?, movie: Bool)
    func getDatabaseData() -> [MoviesValue]?
}

//MARK: Interactor -
protocol ProfileInteractorProtocol: AnyObject {
    
    var presenter: ProfilePresenterProtocol?  { get set }
    func getDatabaseData() -> [MoviesValue]?
}

//MARK: View -
protocol ProfileViewProtocol: AnyObject {
    
    var presenter: ProfilePresenterProtocol?  { get set }
}
