//
//  ProfileInteractor.swift
//  prueba-coppel
//
//  Created Pedro Soriano on 28/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileInteractor: ProfileInteractorProtocol {

    weak var presenter: ProfilePresenterProtocol?
    
    func getDatabaseData() -> [MoviesValue]? {
        do {
            let table = try PersonalDataDataBase.shared.getAllFields(in: .personalData)
            debugPrint("DEBUG: The Table", table)
            return table
        } catch {
            debugPrint("DEBUG: DB unable to get all fields", error)
        }
        return nil
    }
}
