//
//  LoginViewController.swift
//  prueba-coppel
//
//  Created Pedro Soriano on 27/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Firebase
import FirebaseAuth

class LoginViewController: UIViewController, LoginViewProtocol {
    
    //MARK: Properties
    var presenter: LoginPresenterProtocol?
    
    lazy var backgroundImage: UIImageView = {
        let image = UIImageView()
        image.image = UIImage(named: "login.png", in: Bundle(for: LoginViewController.self), compatibleWith: nil)
        image.translatesAutoresizingMaskIntoConstraints = false
        image.contentMode = .scaleAspectFill
        return image
    }()
    
    lazy var nameField: UITextField = {
        let field = UITextField()
        field.backgroundColor = .white
        field.layer.cornerRadius = 5.0
        field.placeholder = " UserName"
        field.translatesAutoresizingMaskIntoConstraints = false
        return field
    }()
    
    lazy var passwordField: UITextField = {
        let field = UITextField()
        field.backgroundColor = .white
        field.layer.cornerRadius = 5.0
        field.placeholder = " Password"
        field.isSecureTextEntry = true
        field.translatesAutoresizingMaskIntoConstraints = false
        return field
    }()
    
    lazy var nextButton: UIButton = {
        let button = UIButton()
        button.backgroundColor = .lightGray
        button.setTitle("Log in", for: .normal)
        button.addTarget(self, action: #selector(nextAction), for: .touchUpInside)
        button.translatesAutoresizingMaskIntoConstraints = false
        return button
    }()
    
    // MARK: View Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setConstraints()
    }
    
    // MARK: Add Constraints
    private func setConstraints(){
        view.addSubview(backgroundImage)
        view.addSubview(nameField)
        view.addSubview(passwordField)
        view.addSubview(nextButton)
        
        NSLayoutConstraint.activate([
            backgroundImage.topAnchor.constraint(equalTo: view.topAnchor),
            backgroundImage.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            backgroundImage.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            backgroundImage.bottomAnchor.constraint(equalTo: view.bottomAnchor)
        ])
        
        NSLayoutConstraint.activate([
            nameField.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            nameField.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            nameField.widthAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0.80),
            nameField.heightAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0.14),
        ])
        
        NSLayoutConstraint.activate([
            passwordField.topAnchor.constraint(equalTo: nameField.bottomAnchor, constant: 20.0),
            passwordField.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            passwordField.widthAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0.80),
            passwordField.heightAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0.14),
        ])
        
        NSLayoutConstraint.activate([
            nextButton.topAnchor.constraint(equalTo: passwordField.bottomAnchor, constant: 20.0),
            nextButton.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            nextButton.widthAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0.80),
            nextButton.heightAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0.15),
        ])
    }
    
    // MARK: Validation Login
    private func loginValidation(email: String, password: String){
        Auth.auth().signIn(withEmail: email, password: password) { [weak self] results, error  in
            if error == nil{
                self?.presenter?.goToHome()
            }else{
                self?.showAlert(title: "warning", message: "your email or password is incorrect")
            }
        }
    }
    
    // MARK: Log in Action
    @objc
    func nextAction(){
        guard let name = nameField.text, let pass = passwordField.text,
              name != "", pass != "" else {
            showAlert(title: "warning", message: "add email and password")
            return
        }
        loginValidation(email: name, password: pass)
    }
    
}
