//
//  HomeProtocols.swift
//  prueba-coppel
//
//  Created Pedro Soriano on 27/09/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {
    func goToDetailMovies(id: Int?, movie: Bool?)
    func goToDetailTV(id: Int?, movie: Bool?)
    func goToProfile()
}
//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject{
    func fetchMovies(type: typeMovies)
    func fetchTV(type: typeTV)
    func responseMovies(data: MoviesResponse)
    func responseTV(data: TVResponse)
    func goToDetailMovies(id: Int?, movie: Bool?)
    func goToDetailTV(id: Int?, movie: Bool?)
    func initDateBase()
    func updateDatabase(values: [MoviesValue])
    func updateDatabase(_ value: MoviesValue)
    func getDatabaseData() -> [MoviesValue]?
    func goToProfile()
    func deleteRowData(_ id: Int)
    func showError(title: String)
}

//MARK: Interactor -
protocol HomeInteractorProtocol: AnyObject {
    
    var presenter: HomePresenterProtocol?  { get set }
    func fetchMovies(type: typeMovies)
    func fetchTV(type: typeTV)
    func initDateBase()
    func updateDatabase(values: [MoviesValue])
    func updateDatabase(_ value: MoviesValue) 
    func getDatabaseData() -> [MoviesValue]?
    func deleteRowData(_ id: Int)
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {
    
    var presenter: HomePresenterProtocol?  { get set }
    func responseMovies(data: MoviesResponse)
    func responseTV(data: TVResponse)
    func showError(title: String)
}
